config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#home'
  resources :doses

  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true
  validates_uniqueness_of :name
  has_many_attached :images
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[ show edit update destroy ]

  # GET /cocktails or /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1 or /cocktails/1.json
  def show
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
  end

  # POST /cocktails or /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: "Cocktail was successfully created." }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1 or /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: "Cocktail was successfully updated." }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1 or /cocktails/1.json
  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: "Cocktail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cocktail_params
      params.require(:cocktail).permit(:name, images: [])
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: %i[ show edit update destroy ]

  # GET /doses/new
  def new
    # we need @cocktail in our `simple_form_for`
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  # POST /doses or /doses.json
  def create
    @dose = Dose.new(dose_params)
    # params[:cocktail_id] = params[:dose][:cocktail_id]
    # puts params
    unless params[:cocktail_id]
      params[:cocktail_id] = params[:dose][:cocktail_id]
    end

     # we need `cocktail_id` to associate dose with corresponding cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])

    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  # PATCH/PUT /doses/1 or /doses/1.json
  def update
    respond_to do |format|
      if @dose.update(dose_params)
        format.html { redirect_to @dose, notice: "Dose was successfully updated." }
        format.json { render :show, status: :ok, location: @dose }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dose.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doses/1 or /doses/1.json
  def destroy
    @dose.destroy
    respond_to do |format|
      format.html { redirect_to doses_url, notice: "Dose was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dose
      @dose = Dose.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dose_params
      params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="form-inputs">
    <%= f.input :images, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-dark mt-4"  %>
  </div>

<% end %>

app/views/cocktails/edit.html.erb
<div class="container">
  <h1>Editing Cocktail</h1>

  <%= render 'form', cocktail: @cocktail %>

  <%= link_to 'Back', cocktails_path, class:"btn btn-dark mt-4" %>

</div>

app/views/cocktails/home.html.erb
<div class="bg">
  <div class="container home-grid">
    <div></div>
    <div>
      <%= link_to "Try our cocktails", cocktails_path, class:"btn btn-dark" %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="container">
  <h1>OUR SPECIALITIES</h1>
  <div class="row d-flex">

    <% @cocktails.each do |cocktail| %>
      <div class="col-12 col-md-6 col-lg-3 mt-4">
      <%= link_to cocktail, class:'card' do %>
        <% if cocktail.images.attached? %>
          <%= cl_image_tag(cocktail.images.first.key, class: 'card-img-top') %>
        <% end %>
        <div class="card-body">
          <h2 class="card-title text-center"><%= cocktail.name %></h2>
        </div>
      <% end %>
      </div>
    <% end %>


  </div>
  <h3 class="mt-5">Didn't find what you wanted? </h3>
  <%= link_to 'Create your own cocktail', new_cocktail_path, class:"btn btn-dark"  %>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>New Cocktail</h1>

  <%= render 'form', cocktail: @cocktail %>

  <%= link_to 'Back', cocktails_path, class:"btn btn-dark mt-4" %>
</div>

app/views/cocktails/show.html.erb
<div class="container p-4">

  <h1 class="mt-2"><%= @cocktail.name %></h1>
  <!-- only want to display the photos if the instance has them, otherwise our code will break -->
  <% if @cocktail.images.attached? %>
    <% @cocktail.images.each do |image| %>
      <%= cl_image_tag(image.key, width: 400, height: 300, crop: :fill) %>
    <% end %>
  <% end %>
  <h2 class="my-2">Ingredients</h2>
  <% @cocktail.doses.each do |dose| %>
    <h3><%= dose.description%> - <%= dose.ingredient.name%></h3>
  <% end %>

  <div>
    <%= link_to 'Add the ingredients', new_cocktail_dose_path(@cocktail), class:"btn btn-dark mt-4" %>
  </div>
  <div>
    <%= link_to 'Back', cocktails_path, class:"btn btn-dark mt-4"  %>
    <%= link_to 'Edit', edit_cocktail_path(@cocktail), class:"btn btn-dark mt-4" %>
    <%= link_to 'Delete', @cocktail, class:"btn btn-dark mt-4", method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for(@dose) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
    <!-- <%= f.association :cocktail %> -->
    <%= f.association :ingredient %>
  </div>
  <%= f.input :cocktail_id, as: :hidden, input_html: { value: params[:cocktail_id] } %>


  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-dark mt-4"%>
  </div>
<% end %>

app/views/doses/edit.html.erb
<h1>Editing Dose</h1>

<%= render 'form', dose: @dose %>

<%= link_to 'Show', @dose %> |
<%= link_to 'Back', doses_path %>

app/views/doses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doses</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Cocktail</th>
      <th>Ingredient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doses.each do |dose| %>
      <tr>
        <td><%= dose.description %></td>
        <td><%= dose.cocktail_id %></td>
        <td><%= dose.ingredient_id %></td>
        <td><%= link_to 'Show', dose %></td>
        <td><%= link_to 'Edit', edit_dose_path(dose) %></td>
        <td><%= link_to 'Destroy', dose, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dose', new_dose_path %>

app/views/doses/new.html.erb
<div class="container">
  <h1>New Dose</h1>
  <%= render 'form', dose: @dose %>
</div>

app/views/doses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @dose.description %>
</p>

<p>
  <strong>Cocktail:</strong>
  <%= @dose.cocktail_id %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @dose.ingredient_id %>
</p>

<%= link_to 'Edit', edit_dose_path(@dose) %> |
<%= link_to 'Back', doses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Boogaloo&display=swap" rel="stylesheet">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container">
    <a class="navbar-brand text-white" href="#">Navbar</a>
  </div>
</nav>